const fullName = "Mark Honchar";
const age = 15;
const profession = "Disigner";
const filmName = "BEE Movie";
const yearOut = 2019;
const awarrdsFilmOscar = false;
let isOscarWin;
isOscarWin = true;
let tempretreOutsideTommorow;
tempretreOutsideTommorow = "28celsi";
const pagesBook = 157;
const isCar = false;
let averageScore;
const isDriverPass = true;
let welcomeWord;
const isAdult = false;
let isPass;
const sportName = "Football";
const isSportOlimpick = true;
const serialName = "Loki";
const amountSeason = 2;
let isFinishedSerial = undefined;
console.log(serialName, amountSeason, isFinishedSerial);

const countryName = 'U"S"A';
const daysVacation = 14;
const isFly = true;
